name: Build

on:
  push:
    branches:
      - "*"
jobs:
  build:
    name: Build binaries
    runs-on: windows-latest
    strategy:
      matrix:
        configuration:
          - Debug
          - Release
    steps:
      - name: Check out files
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
          # NOTE - if LFS ever starts getting used during builds, switch this to true!
          lfs: false

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Download CEF
        run: .\get-cef.ps1
        shell: powershell

      - name: Generate project files
        run: tools/premake5 vs2019

      - name: Set up problem matching
        uses: ammaraskar/msvc-problem-matcher@master

      - name: Build ${{matrix.configuration}} binaries
        run: msbuild /m /v:minimal /p:Configuration=${{matrix.configuration}} /p:Platform=x64 build/launcher.sln

      - name: Upload ${{matrix.configuration}} binaries
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.configuration}} binaries
          path: |
            build/bin/x64/${{matrix.configuration}}/*

      - name: Upload ${{matrix.configuration}} debug symbols
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.configuration}} debug symbols
          path: |
            build/bin/**/*.pdb

      - name: Upload ${{matrix.configuration}} CEF binaries
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.configuration}} CEF
          path: |
            build/runtime/**/*.*

  upload:
    name: Upload artifacts
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out files
        uses: actions/checkout@v2
        with:
          submodules: false
          lfs: false

      - name: Download Release binaries
        uses: actions/download-artifact@v2
        with:
          name: Release binaries

      - name: Download Release CEF binaries
        uses: actions/download-artifact@v2
        with:
          name: Release CEF

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.MASTER_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.MASTER_ADDRESS }} >> ~/.ssh/known_hosts

      #- name: Remove old files on master
      #  run: ssh ${{ secrets.MASTER_USER }}@${{ secrets.MASTER_ADDRESS }} rm -rf /var/www/master.xlabs.dev/data/launcher-ui/*

      - name: Deploy with rsync
        run: rsync -avz xlabs.exe ${{ secrets.MASTER_USER }}@${{ secrets.MASTER_ADDRESS }}:/var/www/master.xlabs.dev/data/

      - name: Trigger cache regeneration
        run: ssh ${{ secrets.MASTER_USER }}@${{ secrets.MASTER_ADDRESS }} node /home/dpmaster/gen.js

  notify:
    name: Notify Discord
    runs-on: ubuntu-latest
    if: |
      github.repository_owner == 'XLabsProject' && (
        (
          github.event.pull_request.merged
        ) || (
          github.event.push.ref == 'refs/heads/master' ||
          github.event.push.ref == 'refs/heads/develop'
        )
      )
    steps:
      - name: Post CI status notification to Discord
        uses: sarisia/actions-status-discord@v1.7.1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_CI_BOT_WEBHOOK }}
          title: "Build"
