name: Build

on:
  push:
    branches:
      - "master"

jobs:
  modify:
    runs-on: ubuntu-latest
    name: Upload data
    steps:
      - name: Check out files
        uses: actions/checkout@v2
        with:
          submodules: false
          lfs: false
