name: Build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
    types: [opened, synchronize, reopened]
jobs:
  modify:
    runs-on: ubuntu-latest
    name: Apply Git modifications if any are necessary
    steps:
      - name: Check out files
        uses: actions/checkout@v2
        with:
          submodules: false
          lfs: false

      - name: Test
        run: echo "${{ github.base_ref }}"

      # Set up committer info and GPG key
      - name: Import GPG key
        if: github.event.pull_request.merged && github.base_ref == 'master'
        id: import_gpg
        uses: XLabsProject/ghaction-import-gpg@25d9d6ab99eb355c169c33c2306a72df85d9f516
        with:
          git-commit-gpgsign: true
          git-committer-email: "${{ secrets.XLABS_CI_EMAIL }}"
          git-committer-name: "${{ secrets.XLABS_CI_NAME }}"
          git-push-gpgsign: false
          git-tag-gpgsign: true
          git-user-signingkey: true
          gpg-private-key: ${{ secrets.XLABS_CI_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.XLABS_CI_GPG_PASSWORD }}

      - name: Extract version from pull request
        if: github.event.pull_request.merged && github.base_ref == 'master'
        id: extract_version
        run: |
          title="${{ github.event.pull_request.title }}"
          version="${title#Release }"
          echo "::set-output name=version::$version"

      - name: Create annotated tag
        if: github.event.pull_request.merged && github.base_ref == 'master'
        run: |
          git tag -a -m "${{ github.event.pull_request.title }}" \
            "${{ steps.extract_version.outputs.version }}" \
            "${{ github.event.pull_request.merge_commit_sha }}"
          git push origin --tags

  build:
    name: Build binaries
    needs: modify
    runs-on: windows-latest
    strategy:
      matrix:
        configuration:
          - Debug
          - Release
    steps:
      - name: Check out files
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
          # NOTE - If LFS ever starts getting used during builds, switch this to true!
          lfs: false

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Download CEF
        run: .\get-cef.ps1
        shell: powershell

      - name: Generate project files
        run: tools/premake5 vs2019 --ci-build

      - name: Set up problem matching
        uses: ammaraskar/msvc-problem-matcher@master

      - name: Build ${{matrix.configuration}} binaries
        run: msbuild /m /v:minimal /p:Configuration=${{matrix.configuration}} /p:Platform=x64 build/launcher.sln

      - name: Upload ${{matrix.configuration}} UI artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.configuration}} UI artifacts
          path: |
            src/launcher-ui/*

      - name: Upload ${{matrix.configuration}} binaries
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.configuration}} binaries
          path: |
            build/bin/x64/${{matrix.configuration}}/xlabs.exe
            build/bin/x64/${{matrix.configuration}}/xlabs.pdb

      - name: Upload ${{matrix.configuration}} CEF binaries
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.configuration}} CEF
          path: |
            build/runtime/x64/${{matrix.configuration}}/*

  deploy:
    name: Deploy artifacts
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop')
    steps:
      - name: Setup main environment
        if: github.ref == 'refs/heads/master'
        run: echo "XLABS_MASTER_PATH=${{ secrets.XLABS_MASTER_SSH_PATH }}" >> $GITHUB_ENV

      - name: Setup develop environment
        if: github.ref == 'refs/heads/develop'
        run: echo "XLABS_MASTER_PATH=${{ secrets.XLABS_MASTER_SSH_PATH_DEV }}" >> $GITHUB_ENV

      - name: Download Release UI artifacts
        uses: actions/download-artifact@v2
        with:
          name: Release UI artifacts
          path: ui

      - name: Download Release binaries
        uses: actions/download-artifact@v2
        with:
          name: Release binaries

      - name: Download Release CEF binaries
        uses: actions/download-artifact@v2
        with:
          name: Release CEF

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.XLABS_MASTER_SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Add known hosts
        run: ssh-keyscan -H ${{ secrets.XLABS_MASTER_SSH_ADDRESS }} >> ~/.ssh/known_hosts

      - name: Wait for previous workflows
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove old CEF artifacts
        run: ssh ${{ secrets.XLABS_MASTER_SSH_USER }}@${{ secrets.XLABS_MASTER_SSH_ADDRESS }} rm -rf ${{ env.XLABS_MASTER_PATH }}/cef/release/*

      - name: Remove old UI artifacts
        run: ssh ${{ secrets.XLABS_MASTER_SSH_USER }}@${{ secrets.XLABS_MASTER_SSH_ADDRESS }} rm -rf ${{ env.XLABS_MASTER_PATH }}/launcher-ui/*

      - name: Upload UI artifacts
        run: rsync -avz ./ui/ ${{ secrets.XLABS_MASTER_SSH_USER }}@${{ secrets.XLABS_MASTER_SSH_ADDRESS }}:${{ env.XLABS_MASTER_PATH }}/launcher-ui/

      - name: Upload CEF binaries
        run: rsync -avz ./cef/ ${{ secrets.XLABS_MASTER_SSH_USER }}@${{ secrets.XLABS_MASTER_SSH_ADDRESS }}:${{ env.XLABS_MASTER_PATH }}/cef/release/

      - name: Upload launcher binary
        run: rsync -avz xlabs.exe ${{ secrets.XLABS_MASTER_SSH_USER }}@${{ secrets.XLABS_MASTER_SSH_ADDRESS }}:${{ env.XLABS_MASTER_PATH }}/

      - name: Publish changes
        run: ssh ${{ secrets.XLABS_MASTER_SSH_USER }}@${{ secrets.XLABS_MASTER_SSH_ADDRESS }} ${{ secrets.XLABS_MASTER_SSH_CHANGE_PUBLISH_COMMAND }}